# Generated by Django 6.0.3 on 2026-03-17 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("anger", "Anger"),
                            ("disgust", "Disgust"),
                            ("fear", "Fear"),
                            ("happiness", "Happiness"),
                            ("sadness", "Sadness"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                (
                    "sleep_quality",
                    models.IntegerField(
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Medium"),
                            (4, "High"),
                            (5, "Very High"),
                        ]
                    ),
                ),
                ("dreamed_at", models.DateTimeField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("lucidity", models.IntegerField()),
                ("nightmare", models.BooleanField()),
                (
                    "colour",
                    models.CharField(
                        choices=[
                            ("#444444", "Charcoal"),
                            ("#f29ab5", "Dream Pink"),
                            ("#7fb8ff", "Sky Blue"),
                            ("#82d6a3", "Soft Green"),
                            ("#ffd36b", "Golden Dream"),
                            ("#bfa3ff", "Lavender"),
                            ("#ff9aa2", "Rose"),
                            ("#7ed9c4", "Mint"),
                        ],
                        default="#000000",
                        max_length=7,
                    ),
                ),
                ("recurring", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dreams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emotions",
                    models.ManyToManyField(
                        related_name="dreams", to="lunar_somnio.emotion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DreamAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentiment_score", models.IntegerField()),
                (
                    "dream",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lunar_somnio.dream",
                    ),
                ),
                (
                    "top_emotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lunar_somnio.emotion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("bio", models.TextField()),
                ("profile_pic", models.URLField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moon_phase", models.CharField(max_length=255)),
                ("moon_illumination", models.IntegerField()),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dream",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lunar_somnio.dream",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        choices=[
                            ("heart", "❤️"),
                            ("laugh", "😂"),
                            ("surprised", "😮"),
                            ("sad", "😢"),
                            ("fire", "🔥"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="lunar_somnio.dream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "dream", "emoji")},
            },
        ),
    ]
