# Generated by Django 2.1.5 on 2026-03-02 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('sleep_quality', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')])),
                ('dreamed_at', models.DateTimeField()),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('lucidity', models.IntegerField()),
                ('nightmare', models.BooleanField()),
                ('colour', models.CharField(max_length=255)),
                ('recurring', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DreamAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.IntegerField()),
                ('dream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lunar_somnio.Dream')),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('anger', 'Anger'), ('disgust', 'Disgust'), ('fear', 'Fear'), ('happiness', 'Happiness'), ('sadness', 'Sadness'), ('neutral', 'Neutral')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('heart', '❤️'), ('laugh', '😂'), ('surprised', '😮'), ('sad', '😢'), ('fire', '🔥')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunar_somnio.Dream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('bio', models.TextField()),
                ('profile_pic', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moon_phase', models.CharField(max_length=255)),
                ('moon_illumination', models.IntegerField()),
                ('dream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lunar_somnio.Dream')),
            ],
        ),
        migrations.AddField(
            model_name='dreamanalysis',
            name='top_emotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunar_somnio.Emotion'),
        ),
        migrations.AddField(
            model_name='dream',
            name='emotions',
            field=models.ManyToManyField(blank=True, related_name='dreams', to='lunar_somnio.Emotion'),
        ),
        migrations.AddField(
            model_name='dream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'dream', 'emoji')},
        ),
    ]
