# Generated by Django 2.1.5 on 2026-03-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar_somnio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='name',
        ),
        migrations.AlterField(
            model_name='dream',
            name='colour',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='dream',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
