# Generated by Django 2.1.5 on 2026-03-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar_somnio', '0002_auto_20260315_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='category',
            field=models.CharField(choices=[('Anger', 'Anger'), ('Disgust', 'Disgust'), ('Fear', 'Fear'), ('Happiness', 'Happiness'), ('Sadness', 'Sadness'), ('Neutral', 'Neutral')], max_length=10),
        ),
    ]
