# Generated by Django 2.1.5 on 2026-03-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar_somnio', '0003_auto_20260315_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
