# Generated by Django 2.1.5 on 2026-03-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar_somnio', '0004_auto_20260316_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersnapshot',
            name='moonrise',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='moonset',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='sunrise',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='sunset',
            field=models.CharField(max_length=255),
        ),
    ]
