# Generated by Django 2.1.5 on 2026-03-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar_somnio', '0005_auto_20260316_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathersnapshot',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
